### ISSUE TITLE
Internet timeout?

### ISSUE THREAD

**Issue by samjango** [ekzhang/bore#95] opened 2023-08-12 20:41 UTC
Hey, been wondering if I can increase the time before bore timeouts as my internet drops regularly and it times out with no restart. Is there a line of code I can edit to make it it take longer or turn off that feature?

**Comment by ekzhang** [comment] 2023-11-13 16:57
Duplicate of #91.

**Closed by ekzhang** 2023-11-13 16:57 UTC

**Comment by samjango** [comment] 2023-11-13 17:21
> Duplicate of #91.

Thank you ill have a look. 😁
