### ISSUE TITLE
how to start bore server that listen on ipv6?

### ISSUE THREAD

**Issue by xshadowlegendx** [ekzhang/bore#86] opened 2023-06-07 06:44 UTC
hello, is there way to tell bore server to listen on ipv6 instead of ipv4? there seems to be no such option when checking bore cli help command

**Comment by ekzhang** [comment] 2023-06-07 20:42
Unfortunately not. This dual-stack use used to be supported, but then it turns out that it doesn't work on [Windows](https://github.com/ekzhang/bore/pull/35).

**Comment by XiaMoHuaHuo-CN** [comment] 2023-07-30 17:23
https://github.com/XMNwWC/boreV6

**Comment by XiaMoHuaHuo-CN** [comment] 2023-07-30 17:27
![Uploading image.png…]()
It works well in my Windows NT/11 PC. ovo

**Comment by MeesJ** [comment] 2023-12-13 20:23
> Unfortunately not. This dual-stack use used to be supported, but then it turns out that it doesn't work on [Windows](https://github.com/ekzhang/bore/pull/35).

With all due respects, why didn't you decide to solve the root cause of the problem instead? Your tool is amazing but I currently can't use it due to the lack of support for IPv6, which is very disappointing.

**Comment by ekzhang** [comment] 2024-09-04 16:23
I'm closing because additional options are not in scope for bore. It's a small program and meant to be read/forked if you have more particular use cases.

I don't have the resources to maintain a general-purpose tool, and I think something like this is better built for your specific use case regardless

**Closed by ekzhang** 2024-09-04 16:23 UTC
