### ISSUE TITLE
Minimum port is ignored if port on local is 0

### ISSUE THREAD

**Issue by BxOxSxS** [ekzhang/bore#23] opened 2022-04-13 16:28 UTC
Hello,
I was trying to add option for max port however I discovered issue and wanted to discuss it before any action.

When you set minimum port on server and the client send wanted port using `-p` option the server correctly check if it's in range or not. 

But when the port is set to 0 (or not given) by local the check is skipped because of condition:
```rust
if port != 0 && port < self.min_port {
```
Port is selected by `TcpListener` from tokio which is bypassing the setting.

The simplest solution that came to my mind is to generate random port on server within given range so currently MIN_PORT and 65535

What do you think?

**Comment by BxOxSxS** [comment] 2022-04-13 16:40
Steps to reproduce:
- run `bore server --min-port 65535` on server
- run `bore local --to <server ip> <any port> -p 65534` on local
You can see it does not work and there is proper message on the server
- run `bore local --to <server ip> <any port> -p 0` on local
You can see assigned port is in most cases under MIN_PORT value

**Comment by ekzhang** [comment] 2022-04-14 18:51
Hi @BxOxSxS, this is actually intended behavior. `min_port` is only used to specify port numbers specified by the user `bore local ... --port x` that are accepted. Unfortunately I don't believe it's possible to ask the operating system for a TCP listener on any given port `:0` with the added constraint of being within a _range of port numbers_.

**Comment by BxOxSxS** [comment] 2022-04-14 19:28
Yes it's not possible that way but bore could somehow choose and assign specyfic port if local gave value 0. Currently`--min-port` option is much less useful that it could be and description can also lead to missunderstanding. It can be problematic with firewalls and general management of server

**Comment by ekzhang** [comment] 2022-04-14 19:34
> Yes it's not possible that way but bore could somehow choose and assign specyfic port if local gave value 0. 

I don't believe this is possible, but if you have a specific technical approach to doing this then we can reopen. Closing this issue.

**Closed by ekzhang** 2022-04-14 19:34 UTC

**Comment by BxOxSxS** [comment] 2022-04-14 21:18
Here is more technical example:
https://github.com/rust-lang-nursery/rust-cookbook/issues/500

I tried that first approach with for loop and it's working fine under linux but does now work on windows as someone commented on the issue. I will try to experiment with second way and report back

**Comment by DesignsWithDavid** [comment] 2023-04-06 15:22
Here is a means of limiting random port selection to a range via "ip_local_port_range": https://unix.stackexchange.com/questions/305308/how-to-limit-range-of-random-port-sockets
